### ISSUE TITLE
KeyError: 'source' when trying to scrape

### ISSUE THREAD

**Issue by ictos** [Voldrix/onlyfans-dl-2#141]
Was working fine at the weekend but whenever I try to run it tonight I get this-
```
./onlyfans-dl.py <redacted> max_age = 10
CWD = /home/ictos/onlyfans-dl-2

Getting posts newer than 2024-08-10 17:47:18 UTC

<redacted> exists.
Downloading new media, skipping pre-existing.
Found 5 posts
Traceback (most recent call last):
  File "/home/ictos/onlyfans-dl-2/./onlyfans-dl.py", line 312, in <module>
    get_content("posts", "/users/" + PROFILE_ID + "/posts")
  File "/home/ictos/onlyfans-dl-2/./onlyfans-dl.py", line 255, in get_content
    download_media(media, MEDIATYPE, postdate, album)
  File "/home/ictos/onlyfans-dl-2/./onlyfans-dl.py", line 178, in download_media
    source = media["source"]["source"]
KeyError: 'source'

```
I've tried updating the session & cookie variables but nothing seems to work.

**Comment by Houkannis** [comment]
I'm experiencing the same error

**Comment by nofate301** [comment]
+1, I'd guess they changed something in their website and it's breaking the script.

**Comment by Voldrix** [comment]
Minor change to the site's media api json structure. Fix pushed.

**Comment by Houkannis** [comment]
Thanks!

**Comment by nofate301** [comment]
Seems to be working, but I think it's skipping some video content that I don't have.  It's catching up on photos, but some videos are not getting downloaded.

**Comment by Forger7** [comment]
Seems to still crash when downloading stories:

`Downloading new media, skipping pre-existing.
Found 15 posts
Downloaded 0 new posts
Found 1 archived
Downloaded 0 new archived
Found 1 stories
Traceback (most recent call last):
  File "onlyfans-dl.py", line 321, in <module>
    get_content("stories", "/users/" + PROFILE_ID + "/stories")
  File "onlyfans-dl.py", line 260, in get_content
    download_media(media, MEDIATYPE, postdate, album)
  File "onlyfans-dl.py", line 176, in download_media
    source = media["files"]["source"]["url"]
             ~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'source'
`

**Comment by Voldrix** [comment]
I  just pushed the change for stories as well.

As for the missing videos, it is because they are encrypted. The script cannot circumvent the video encryption. It should download the preview image in its place as a placeholder.

**Comment by nemock** [comment]
I tried the code from last night and got this...

Traceback (most recent call last):
  File "/Volumes/Mando/ofdl/onlyfans-dl.py", line 317, in <module>
    get_content("posts", "/users/" + PROFILE_ID + "/posts")
  File "/Volumes/Mando/ofdl/onlyfans-dl.py", line 260, in get_content
    download_media(media, MEDIATYPE, postdate, album)
  File "/Volumes/Mando/ofdl/onlyfans-dl.py", line 195, in download_media
    extension = source.split('?')[0].split('.')
                ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by waswosi** [comment]
> I tried the code from last night and got this...
> 
> Traceback (most recent call last): File "/Volumes/Mando/ofdl/onlyfans-dl.py", line 317, in get_content("posts", "/users/" + PROFILE_ID + "/posts") File "/Volumes/Mando/ofdl/onlyfans-dl.py", line 260, in get_content download_media(media, MEDIATYPE, postdate, album) File "/Volumes/Mando/ofdl/onlyfans-dl.py", line 195, in download_media extension = source.split('?')[0].split('.') ^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'split'

Same here! Please fix voldrix.

**Comment by Hammanek** [comment]
I fixed it here
https://github.com/Voldrix/onlyfans-dl-2/blob/08498d19f955355ef007bd8ec9764891d36e45b5/onlyfans-dl.py

**Comment by Voldrix** [comment]
merged

**Comment by Voldrix** [comment]
I added another small change that fixes the DRM preview image capture for encrypted videos.
